from __future__ import annotations

from typing import Any

from features.model_integrations.model_integration_schema import ModelIntegrationRecord


def _record(
    *,
    model_id: str,
    family: str,
    role: str,
    inputs: list[str],
    outputs: list[str],
    tasks: list[str],
    personalization_path: str,
    safety_policy: str,
    training_allowed: bool = False,
    fine_tune_possible: bool = False,
    smoke_test_supported: bool = False,
    limitations: list[str] | None = None,
) -> ModelIntegrationRecord:
    return ModelIntegrationRecord(
        model_id=model_id,
        family=family,
        role_in_music_brain=role,
        input_modalities=inputs,
        output_modalities=outputs,
        expected_tasks=tasks,
        local_config_required=True,
        weights_required=True,
        training_allowed=training_allowed,
        fine_tune_possible=fine_tune_possible,
        user_personalization_path=personalization_path,
        safety_policy=safety_policy,
        availability_status="unavailable",
        unavailable_reason="disabled_by_default_until_explicitly_configured",
        smoke_test_supported=smoke_test_supported,
        limitations=limitations or ["Disabled by default.", "No implicit package installs or model downloads."],
    )


def list_model_integrations() -> list[ModelIntegrationRecord]:
    return [
        _record(
            model_id="moonbeam",
            family="symbolic_generation",
            role="Primary symbolic composition and continuation backend.",
            inputs=["symbolic_prompt", "symbolic_context"],
            outputs=["symbolic_midi"],
            tasks=["continuation", "infill", "arrangement_sketch"],
            personalization_path="adapter tuning on authorized accepted symbolic outcomes",
            safety_policy="human_review_required_before_training_reuse",
            fine_tune_possible=True,
            smoke_test_supported=True,
        ),
        _record(
            model_id="midigpt",
            family="symbolic_generation",
            role="Controllable multitrack symbolic variation backend.",
            inputs=["symbolic_prompt", "control_signals"],
            outputs=["symbolic_midi"],
            tasks=["drum_multitrack_variation", "track_infill"],
            personalization_path="ranker/controller learning from accepted multitrack edits",
            safety_policy="human_review_required_before_training_reuse",
            fine_tune_possible=True,
            smoke_test_supported=True,
        ),
        _record(
            model_id="text2midi",
            family="symbolic_generation",
            role="Prompt-to-sketch symbolic draft backend.",
            inputs=["text_prompt"],
            outputs=["symbolic_midi"],
            tasks=["prompt_sketch", "motif_draft"],
            personalization_path="prompt/output preference alignment from review labels",
            safety_policy="human_review_required_before_training_reuse",
            fine_tune_possible=True,
            smoke_test_supported=True,
        ),
        _record(
            model_id="musicbert",
            family="symbolic_understanding",
            role="Symbolic representation, similarity, and ranking model.",
            inputs=["symbolic_midi", "symbolic_metadata"],
            outputs=["embedding", "score"],
            tasks=["candidate_ranking", "similarity", "quality_estimation"],
            personalization_path="head/ranker training from accepted-vs-rejected symbolic pairs",
            safety_policy="policy_gated_training_corpus_only",
            training_allowed=True,
            fine_tune_possible=True,
            smoke_test_supported=True,
        ),
        _record(
            model_id="yourmt3",
            family="transcription",
            role="External witness transcription model.",
            inputs=["audio_waveform"],
            outputs=["symbolic_midi", "confidence"],
            tasks=["transcription_witness"],
            personalization_path="none_by_default_transcription_outputs_are_witness_not_truth",
            safety_policy="transcription_witness_not_truth",
            smoke_test_supported=True,
        ),
        _record(
            model_id="basic_pitch",
            family="transcription",
            role="Secondary witness transcription model for agreement checks.",
            inputs=["audio_waveform"],
            outputs=["symbolic_midi", "confidence"],
            tasks=["transcription_witness"],
            personalization_path="none_by_default_transcription_outputs_are_witness_not_truth",
            safety_policy="transcription_witness_not_truth",
            smoke_test_supported=True,
        ),
        _record(
            model_id="muq",
            family="audio_understanding",
            role="Audio understanding encoder for semantic tagging.",
            inputs=["audio_waveform"],
            outputs=["embedding", "tags"],
            tasks=["audio_embedding", "semantic_feature_support"],
            personalization_path="ranker/head tuning from authorized feedback labels",
            safety_policy="policy_gated_training_corpus_only",
            training_allowed=True,
            fine_tune_possible=True,
        ),
        _record(
            model_id="mert",
            family="audio_understanding",
            role="Audio representation model for retrieval and context features.",
            inputs=["audio_waveform"],
            outputs=["embedding"],
            tasks=["audio_embedding", "retrieval_feature_support"],
            personalization_path="ranker/head tuning from authorized feedback labels",
            safety_policy="policy_gated_training_corpus_only",
            training_allowed=True,
            fine_tune_possible=True,
        ),
        _record(
            model_id="essentia",
            family="audio_understanding",
            role="Feature extraction baseline for timbre/rhythm descriptors.",
            inputs=["audio_waveform"],
            outputs=["analysis_features"],
            tasks=["audio_feature_extraction", "descriptor_support"],
            personalization_path="not_a_finetune_target_use_as_fixed_feature_witness",
            safety_policy="feature_witness_only",
            limitations=["Essentia is typically used as a fixed feature extractor."],
        ),
        _record(
            model_id="clap",
            family="audio_text_retrieval",
            role="Audio-text retrieval embedding model.",
            inputs=["audio_waveform", "text_prompt"],
            outputs=["joint_embedding"],
            tasks=["audio_text_similarity", "prompt_to_audio_retrieval"],
            personalization_path="preference-aligned retrieval reranker on authorized user labels",
            safety_policy="policy_gated_training_corpus_only",
            training_allowed=True,
            fine_tune_possible=True,
        ),
        _record(
            model_id="mulan_style",
            family="audio_text_retrieval",
            role="Style-aware retrieval embedding model.",
            inputs=["audio_waveform", "text_prompt"],
            outputs=["joint_embedding"],
            tasks=["style_similarity", "audio_text_retrieval"],
            personalization_path="style preference reranker training from user review outcomes",
            safety_policy="policy_gated_training_corpus_only",
            training_allowed=True,
            fine_tune_possible=True,
        ),
        _record(
            model_id="demucs",
            family="source_separation",
            role="Source separation backend for weak evidence stems.",
            inputs=["audio_waveform"],
            outputs=["audio_stems"],
            tasks=["source_separation"],
            personalization_path="none_by_default_source_separation_is_weak_evidence",
            safety_policy="weak_evidence_requires_review",
        ),
        _record(
            model_id="musicgen",
            family="audio_generation_reference",
            role="Reference-only audio generator for inspiration baselines.",
            inputs=["text_prompt"],
            outputs=["audio_waveform"],
            tasks=["reference_generation"],
            personalization_path="disabled_for_training_reference_only_unless_explicitly_enabled",
            safety_policy="reference_only_unless_explicitly_enabled",
        ),
        _record(
            model_id="audiocraft",
            family="audio_generation_reference",
            role="Reference-only audio generation tooling family.",
            inputs=["text_prompt"],
            outputs=["audio_waveform"],
            tasks=["reference_generation"],
            personalization_path="disabled_for_training_reference_only_unless_explicitly_enabled",
            safety_policy="reference_only_unless_explicitly_enabled",
        ),
        _record(
            model_id="musicgen_stem",
            family="audio_generation_reference",
            role="Stem-oriented reference audio generation backend.",
            inputs=["text_prompt"],
            outputs=["audio_stems"],
            tasks=["reference_generation", "stem_reference_generation"],
            personalization_path="disabled_for_training_reference_only_unless_explicitly_enabled",
            safety_policy="reference_only_unless_explicitly_enabled",
        ),
        _record(
            model_id="texture_embedding_model",
            family="texture_and_sound_selection",
            role="Texture embedding model for sound palette fit.",
            inputs=["audio_metadata", "feature_vectors"],
            outputs=["embedding", "fit_score"],
            tasks=["texture_retrieval", "role_fit_scoring"],
            personalization_path="train rankers from accepted texture placements",
            safety_policy="policy_gated_training_corpus_only",
            training_allowed=True,
            fine_tune_possible=True,
        ),
        _record(
            model_id="synplant_seed_selector",
            family="texture_and_sound_selection",
            role="Synplant seed suggestion ranker under policy constraints.",
            inputs=["seed_metadata", "track_context"],
            outputs=["ranked_seed_candidates"],
            tasks=["seed_selection", "session_seed_planning"],
            personalization_path="train seed usefulness ranker from user feedback",
            safety_policy="synplant_seed_restrictions_inherit_source_policy",
            training_allowed=True,
            fine_tune_possible=True,
        ),
        _record(
            model_id="synplant_patch_ranker",
            family="texture_and_sound_selection",
            role="Synplant patch ranking model for manual outcomes.",
            inputs=["patch_metadata", "track_context"],
            outputs=["ranked_patch_candidates"],
            tasks=["patch_ranking", "manual_render_prioritization"],
            personalization_path="train patch preference model from repeated approvals",
            safety_policy="synplant_seed_restrictions_inherit_source_policy",
            training_allowed=True,
            fine_tune_possible=True,
        ),
        _record(
            model_id="ableton_exporter",
            family="daw_agent_tools",
            role="DAW export bridge for arrangement handoff.",
            inputs=["symbolic_midi", "arrangement_plan"],
            outputs=["daw_project_manifest"],
            tasks=["project_export", "clip_layout_support"],
            personalization_path="preference model on arrangement outcomes",
            safety_policy="no_private_paths_in_public_reports",
            training_allowed=True,
        ),
        _record(
            model_id="max_for_live_bridge",
            family="daw_agent_tools",
            role="Max for Live control bridge.",
            inputs=["agent_actions", "daw_state"],
            outputs=["control_events"],
            tasks=["live_control", "automation_bridge"],
            personalization_path="workflow preference learning from accepted sessions",
            safety_policy="no_private_paths_in_public_reports",
            training_allowed=True,
        ),
        _record(
            model_id="puredata_plugdata_bridge",
            family="daw_agent_tools",
            role="Pure Data / PlugData integration bridge.",
            inputs=["agent_actions", "texture_plan"],
            outputs=["patch_instructions"],
            tasks=["texture_tool_routing", "patch_workflow_bridge"],
            personalization_path="plan ranking from accepted texture outcomes",
            safety_policy="no_private_paths_in_public_reports",
            training_allowed=True,
        ),
    ]


def list_model_families() -> dict[str, list[str]]:
    families: dict[str, list[str]] = {}
    for record in list_model_integrations():
        families.setdefault(record.family, []).append(record.model_id)
    return families


def model_registry_payload() -> dict[str, Any]:
    rows = list_model_integrations()
    return {
        "status": "ok",
        "model_count": len(rows),
        "families": list_model_families(),
        "models": [row.as_dict() for row in rows],
        "limitations": [
            "Registry describes integration intent and safety defaults only.",
            "No model is implicitly enabled or downloaded.",
            "Availability remains unavailable until local config explicitly enables a backend.",
        ],
    }


def model_registry_by_id() -> dict[str, ModelIntegrationRecord]:
    return {row.model_id: row for row in list_model_integrations()}
