from __future__ import annotations

import importlib
import json
from pathlib import Path
from typing import Any

PLACEHOLDERS = {"", "<PATH_TO_MODEL>", "<PATH_TO_REPO>", "<DEVICE>"}


class MERTAdapter:
    model_id = "mert"

    def _config_paths(self) -> tuple[Path, Path]:
        root = Path(__file__).resolve().parents[2]
        config_dir = root / "config" / "model_integrations"
        return config_dir / "model_integrations.local.json", config_dir / "model_integrations.example.json"

    def _load_settings(self) -> tuple[dict[str, Any], bool]:
        local_path, example_path = self._config_paths()
        source = local_path if local_path.exists() else example_path
        if not source.exists():
            return {}, False
        try:
            payload = json.loads(source.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            return {}, bool(local_path.exists())
        models = payload.get("models", {}) if isinstance(payload, dict) else {}
        settings = models.get(self.model_id, {}) if isinstance(models, dict) else {}
        return settings if isinstance(settings, dict) else {}, bool(local_path.exists())

    def _is_real_value(self, value: Any) -> bool:
        return str(value or "").strip() not in PLACEHOLDERS

    def configured(self) -> bool:
        settings, using_local = self._load_settings()
        if not using_local:
            return False
        return (
            bool(settings.get("enabled", False))
            and self._is_real_value(settings.get("repo_path"))
            and self._is_real_value(settings.get("model_path"))
            and self._is_real_value(settings.get("tokenizer_path"))
            and self._is_real_value(settings.get("device"))
            and bool(settings.get("embedding_dim", 0))
            and self._is_real_value(settings.get("output_dir"))
        )

    def run_smoke_test(self) -> tuple[bool, str]:
        settings, using_local = self._load_settings()
        if not using_local:
            return False, "disabled_or_missing_local_config"
        if not bool(settings.get("enabled", False)):
            return False, "disabled_in_local_config"
        if not bool(settings.get("smoke_test_enabled", False)):
            return False, "smoke_test_disabled_in_config"
        if not self.configured():
            return False, "enabled_but_not_fully_configured"
        try:
            importlib.import_module("torch")
        except ModuleNotFoundError:
            return False, "dependency_missing:torch"
        except Exception:  # noqa: BLE001
            return False, "dependency_probe_failed:torch"
        return True, "smoke_test_passed"

    def availability(self) -> dict[str, Any]:
        configured = self.configured()
        passed, reason = self.run_smoke_test()
        return {
            "configured": configured,
            "available": bool(passed),
            "reason": reason,
            "role": "future_representation_embedding_encoder",
            "notes": [
                "Scaffold only; no embeddings are generated by this adapter.",
                "No audio processing, no downloads, and no training are performed.",
            ],
        }
