from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

REPORT_DIR = ROOT_DIR / "reports" / "audio_understanding"
PRIVATE_PATH_MARKERS = (":/Users/", "\\Users\\")
TRAINING_EXCLUSION_POLICIES = [
    "splice_production_only",
    "production_only_training_excluded",
]


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _is_private_path(value: str) -> bool:
    return any(marker in value for marker in PRIVATE_PATH_MARKERS)


def _safe_ref(path: Path) -> str:
    rel = path.relative_to(ROOT_DIR).as_posix()
    return "<REDACTED_PRIVATE_PATH>" if _is_private_path(rel) else rel


def _discover_aggregate_reports() -> list[Path]:
    candidates: list[Path] = []
    scan_roots = [
        ROOT_DIR / "reports" / "texture_intelligence",
        ROOT_DIR / "reports" / "synplant",
        ROOT_DIR / "outputs",
    ]
    for root in scan_roots:
        if not root.exists():
            continue
        candidates.extend(sorted(root.glob("**/*aggregate*.json")))
        candidates.extend(sorted(root.glob("**/*sample*library*.json")))
    unique_paths = sorted({path.resolve() for path in candidates if path.is_file()})
    return [Path(path) for path in unique_paths]


def _collect_policy_counts(payload: Any, counts: dict[str, int]) -> None:
    if isinstance(payload, dict):
        for key, value in payload.items():
            if key == "source_policy" and isinstance(value, str):
                counts[value] = counts.get(value, 0) + 1
            _collect_policy_counts(value, counts)
    elif isinstance(payload, list):
        for item in payload:
            _collect_policy_counts(item, counts)


def build_audio_texture_embedding_plan() -> dict[str, Any]:
    report_paths = _discover_aggregate_reports()
    source_refs: list[str] = []
    source_policy_counts: dict[str, int] = {}
    for path in report_paths:
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            continue
        _collect_policy_counts(payload, source_policy_counts)
        safe_ref = _safe_ref(path)
        if safe_ref != "<REDACTED_PRIVATE_PATH>":
            source_refs.append(safe_ref)

    return {
        "status": "planned",
        "created_at": _now_iso(),
        "source_reports_inspected_count": len(source_refs),
        "source_reports_inspected": sorted(source_refs),
        "source_policy_counts": dict(sorted(source_policy_counts.items())),
        "audio_processing_performed": False,
        "embeddings_generated": False,
        "model_training_has_occurred": False,
        "downloads_performed": False,
        "training_exclusions": {
            "preserved_policies": TRAINING_EXCLUSION_POLICIES,
            "enforcement_notes": [
                "Splice and production-only assets remain excluded from training corpora.",
                "Any future training workflow must enforce source-policy gates before dataset export.",
            ],
        },
        "workflow_plan": [
            "Step 1: Validate local config gates for Essentia, MuQ, and MERT without processing audio.",
            "Step 2: Build an input manifest from authorized aggregate metadata only.",
            "Step 3: Run Essentia descriptor extraction on explicit authorized manifests only.",
            "Step 4: Run MuQ/MERT embedding jobs only when explicitly enabled and reviewed.",
            "Step 5: Store embeddings in local output_dir and keep public reports path-redacted.",
            "Step 6: Keep training disabled unless policy-gated future workflow is approved.",
        ],
        "privacy_source_policy_requirements": [
            "Do not expose private local filesystem paths in public reports.",
            "Only process assets explicitly marked as authorized for the requested operation.",
            "Never treat Splice/production-only assets as training candidates.",
        ],
        "limitations": [
            "Planning only: no audio processing, no transcription, and no Modal calls.",
            "No embedding vectors are generated by this planner.",
            "No model training is performed or claimed.",
        ],
    }


def write_plan_report(output_dir: Path) -> tuple[Path, Path, dict[str, Any]]:
    payload = build_audio_texture_embedding_plan()
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "audio_texture_embedding_plan.json"
    md_path = output_dir / "audio_texture_embedding_plan.md"
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    lines = [
        "# Audio Texture Embedding Plan",
        "",
        f"- status: `{payload['status']}`",
        f"- source_reports_inspected_count: `{payload['source_reports_inspected_count']}`",
        "- audio_processing_performed: `False`",
        "- embeddings_generated: `False`",
        "- model_training_has_occurred: `False`",
        "",
        "## Training Exclusions",
        "- splice_production_only: enforced",
        "- production_only_training_excluded: enforced",
    ]
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return json_path, md_path, payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Plan future audio texture embedding workflow from aggregate local reports.")
    parser.add_argument("--output-dir", default=REPORT_DIR.as_posix())
    args = parser.parse_args()
    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = ROOT_DIR / output_dir
    json_path, md_path, payload = write_plan_report(output_dir)
    print(f"AUDIO_TEXTURE_EMBEDDING_PLAN_JSON={json_path.as_posix()}")
    print(f"AUDIO_TEXTURE_EMBEDDING_PLAN_MD={md_path.as_posix()}")
    print(f"PLAN_STATUS={payload['status']}")
    print("AUDIO_PROCESSING_PERFORMED=False")
    print("EMBEDDINGS_GENERATED=False")
    print("MODEL_TRAINING_HAS_OCCURRED=False")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
