from __future__ import annotations


STANDARD_RHYTHM_FIXTURES: list[dict[str, object]] = [
    {
        "fixture_id": "fx_tresillo",
        "expected_pattern_id": "tresillo_3_3_2",
        "expected_family": "tresillo_3_3_2",
        "meter_context": "4/4",
        "token_pattern": "x..x..x.",
        "accent_pattern": "X..x..x.",
        "interval_ratios": [1.5, 1.5, 1.0],
        "rotations": ["..x..x.x"],
        "negative_families": ["clave"],
        "description": "Canonical tresillo cell.",
        "should_match_strength": "strong",
        "should_not_match": ["clave", "waltz_3_4"],
        "notes": "Rotation invariant.",
    },
    {
        "fixture_id": "fx_habanera",
        "expected_pattern_id": "habanera",
        "expected_family": "habanera",
        "meter_context": "4/4",
        "token_pattern": "x..xx.x.",
        "accent_pattern": "X..xX.x.",
        "interval_ratios": [1.5, 0.5, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["clave"],
        "description": "Habanera contour.",
        "should_match_strength": "strong",
        "should_not_match": ["waltz_3_4"],
        "notes": "",
    },
    {
        "fixture_id": "fx_cinquillo",
        "expected_pattern_id": "cinquillo",
        "expected_family": "cinquillo",
        "meter_context": "2/4",
        "token_pattern": "x.x.x..x.",
        "accent_pattern": "X.x.x..x.",
        "interval_ratios": [1.0, 1.0, 1.0, 2.0, 1.0],
        "rotations": ["..x.x.x..x"],
        "negative_families": ["waltz_3_4"],
        "description": "Cinquillo five-hit asymmetry.",
        "should_match_strength": "strong",
        "should_not_match": ["waltz_3_4"],
        "notes": "",
    },
    {
        "fixture_id": "fx_son_clave_32",
        "expected_pattern_id": "son_clave_3_2",
        "expected_family": "clave",
        "meter_context": "4/4",
        "token_pattern": "x..x...x..x.x...",
        "accent_pattern": "X..x...X..x.x...",
        "interval_ratios": [3.0, 3.0, 4.0, 2.0, 4.0],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2"],
        "description": "Son clave 3-2.",
        "should_match_strength": "strong",
        "should_not_match": ["tresillo_3_3_2"],
        "notes": "",
    },
    {
        "fixture_id": "fx_son_clave_23",
        "expected_pattern_id": "son_clave_2_3",
        "expected_family": "clave",
        "meter_context": "4/4",
        "token_pattern": "x.x...x..x...x..",
        "accent_pattern": "X.x...x..X...x..",
        "interval_ratios": [2.0, 4.0, 3.0, 3.0, 4.0],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2"],
        "description": "Son clave 2-3.",
        "should_match_strength": "strong",
        "should_not_match": ["tresillo_3_3_2"],
        "notes": "",
    },
    {
        "fixture_id": "fx_rumba_clave_32",
        "expected_pattern_id": "rumba_clave_3_2",
        "expected_family": "clave",
        "meter_context": "4/4",
        "token_pattern": "x..x...x.x...x..",
        "accent_pattern": "X..x...x.X...x..",
        "interval_ratios": [3.0, 3.0, 2.0, 4.0, 4.0],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2"],
        "description": "Rumba clave 3-2.",
        "should_match_strength": "moderate",
        "should_not_match": ["tresillo_3_3_2"],
        "notes": "",
    },
    {
        "fixture_id": "fx_rumba_clave_23",
        "expected_pattern_id": "rumba_clave_2_3",
        "expected_family": "clave",
        "meter_context": "4/4",
        "token_pattern": "x...x..x...x.x..",
        "accent_pattern": "X...x..x...X.x..",
        "interval_ratios": [4.0, 3.0, 4.0, 2.0, 3.0],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2"],
        "description": "Rumba clave 2-3.",
        "should_match_strength": "moderate",
        "should_not_match": ["tresillo_3_3_2"],
        "notes": "",
    },
    {
        "fixture_id": "fx_backbeat",
        "expected_pattern_id": "backbeat_2_4",
        "expected_family": "backbeat",
        "meter_context": "4/4",
        "token_pattern": ".x..x...x...x...",
        "accent_pattern": ".x..X...x...X...",
        "interval_ratios": [1.0, 1.0, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["waltz_3_4"],
        "description": "Backbeat accents on 2 and 4 proxies.",
        "should_match_strength": "moderate",
        "should_not_match": ["waltz_3_4"],
        "notes": "",
    },
    {
        "fixture_id": "fx_four_floor",
        "expected_pattern_id": "four_on_the_floor",
        "expected_family": "four_on_the_floor",
        "meter_context": "4/4",
        "token_pattern": "x...x...x...x...",
        "accent_pattern": "X...X...X...X...",
        "interval_ratios": [1.0, 1.0, 1.0, 1.0],
        "rotations": ["...x...x...x...x"],
        "negative_families": ["clave"],
        "description": "Four-on-the-floor quarter pulse.",
        "should_match_strength": "strong",
        "should_not_match": ["clave"],
        "notes": "",
    },
    {
        "fixture_id": "fx_waltz",
        "expected_pattern_id": "waltz_3_4",
        "expected_family": "waltz_3_4",
        "meter_context": "3/4",
        "token_pattern": "x..x..x..",
        "accent_pattern": "X..x..x..",
        "interval_ratios": [1.0, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["clave"],
        "description": "Simple 3/4 waltz pulse.",
        "should_match_strength": "strong",
        "should_not_match": ["clave"],
        "notes": "",
    },
    {
        "fixture_id": "fx_march",
        "expected_pattern_id": "march_duple",
        "expected_family": "march_duple",
        "meter_context": "2/4",
        "token_pattern": "x.x.x.x.",
        "accent_pattern": "X.x.X.x.",
        "interval_ratios": [1.0, 1.0, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["shuffle"],
        "description": "Duple march pulse.",
        "should_match_strength": "moderate",
        "should_not_match": ["shuffle"],
        "notes": "",
    },
    {
        "fixture_id": "fx_shuffle",
        "expected_pattern_id": "swing_shuffle",
        "expected_family": "shuffle",
        "meter_context": "12/8",
        "token_pattern": "x..x..x..x..",
        "accent_pattern": "X..x..X..x..",
        "interval_ratios": [0.667, 0.333, 0.667, 0.333],
        "rotations": [],
        "negative_families": ["march_duple"],
        "description": "Shuffle long-short feel.",
        "should_match_strength": "moderate",
        "should_not_match": ["march_duple"],
        "notes": "",
    },
    {
        "fixture_id": "fx_128_gospel",
        "expected_pattern_id": "twelve_eight_gospel",
        "expected_family": "twelve_eight_gospel",
        "meter_context": "12/8",
        "token_pattern": "x..x..x..x..",
        "accent_pattern": "X..x..X..x..",
        "interval_ratios": [3.0, 3.0, 3.0, 3.0],
        "rotations": [],
        "negative_families": ["march_duple"],
        "description": "12/8 gospel pulse.",
        "should_match_strength": "moderate",
        "should_not_match": ["march_duple"],
        "notes": "",
    },
    {
        "fixture_id": "fx_gospel_backbeat",
        "expected_pattern_id": "gospel_clap_backbeat",
        "expected_family": "gospel_clap_backbeat",
        "meter_context": "4/4",
        "token_pattern": ".x..x...x...x...",
        "accent_pattern": ".x..X...x...X...",
        "interval_ratios": [1.0, 1.0, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["four_on_the_floor"],
        "description": "Gospel backbeat clap contour.",
        "should_match_strength": "moderate",
        "should_not_match": ["four_on_the_floor"],
        "notes": "",
    },
    {
        "fixture_id": "fx_boom_bap",
        "expected_pattern_id": "boom_bap_backbeat",
        "expected_family": "boom_bap_backbeat",
        "meter_context": "4/4",
        "token_pattern": "x...x...x...x...",
        "accent_pattern": "X...x...X...x...",
        "interval_ratios": [1.0, 1.0, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["clave"],
        "description": "Boom bap kick/snare proxy.",
        "should_match_strength": "moderate",
        "should_not_match": ["clave"],
        "notes": "",
    },
    {
        "fixture_id": "fx_trap_subdiv",
        "expected_pattern_id": "trap_hihat_subdivision",
        "expected_family": "trap_subdivision",
        "meter_context": "4/4",
        "token_pattern": "x.x.x.x.x.x.x.x.",
        "accent_pattern": "x.X.x.X.x.X.x.X.",
        "interval_ratios": [0.5, 0.5, 0.5, 0.5],
        "rotations": [],
        "negative_families": ["waltz_3_4"],
        "description": "High subdivision trap hi-hat pattern.",
        "should_match_strength": "moderate",
        "should_not_match": ["waltz_3_4"],
        "notes": "",
    },
    {
        "fixture_id": "fx_dembow",
        "expected_pattern_id": "dembow_like",
        "expected_family": "dembow_like",
        "meter_context": "4/4",
        "token_pattern": "x..x...x..x.x...",
        "accent_pattern": "X..x...x..X.x...",
        "interval_ratios": [3.0, 4.0, 3.0, 2.0, 4.0],
        "rotations": ["..x...x..x.x...x"],
        "negative_families": ["waltz_3_4"],
        "description": "Dembow-like asymmetry.",
        "should_match_strength": "moderate",
        "should_not_match": ["waltz_3_4"],
        "notes": "",
    },
    {
        "fixture_id": "fx_bossa",
        "expected_pattern_id": "bossa_like",
        "expected_family": "bossa_like",
        "meter_context": "4/4",
        "token_pattern": "x..x.x...x.x....",
        "accent_pattern": "X..x.x...x.X....",
        "interval_ratios": [3.0, 2.0, 4.0, 2.0, 5.0],
        "rotations": [],
        "negative_families": ["four_on_the_floor"],
        "description": "Bossa-like syncopated contour.",
        "should_match_strength": "moderate",
        "should_not_match": ["four_on_the_floor"],
        "notes": "",
    },
    {
        "fixture_id": "fx_samba",
        "expected_pattern_id": "samba_like",
        "expected_family": "samba_like",
        "meter_context": "2/4",
        "token_pattern": "x.x..x.x..x.x..",
        "accent_pattern": "X.x..x.X..x.x..",
        "interval_ratios": [1.0, 2.0, 1.0, 2.0, 1.0],
        "rotations": [],
        "negative_families": ["march_duple"],
        "description": "Samba-like interlocking pattern.",
        "should_match_strength": "moderate",
        "should_not_match": ["march_duple"],
        "notes": "",
    },
    {
        "fixture_id": "fx_vamp",
        "expected_pattern_id": "generic_vamp_cycle",
        "expected_family": "generic_vamp_cycle",
        "meter_context": "4/4",
        "token_pattern": "x...x...x...x...",
        "accent_pattern": "X...x...X...x...",
        "interval_ratios": [1.0, 1.0, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["clave"],
        "description": "Generic repeated vamp cycle.",
        "should_match_strength": "moderate",
        "should_not_match": ["clave"],
        "notes": "",
    },
    {
        "fixture_id": "fx_sparse_call_response",
        "expected_pattern_id": "sparse_call_response",
        "expected_family": "sparse_call_response",
        "meter_context": "free",
        "token_pattern": "x....x....",
        "accent_pattern": "X....x....",
        "interval_ratios": [2.0, 2.0],
        "rotations": [],
        "negative_families": ["trap_subdivision"],
        "description": "Sparse call-response contour.",
        "should_match_strength": "moderate",
        "should_not_match": ["trap_subdivision"],
        "notes": "",
    },
    # Negative controls
    {
        "fixture_id": "neg_all_onset_xxxx",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "any",
        "token_pattern": "xxxx",
        "accent_pattern": "XXXX",
        "interval_ratios": [],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2", "clave", "cinquillo"],
        "description": "All onset 4-step.",
        "should_match_strength": "weak",
        "should_not_match": ["tresillo_3_3_2", "clave", "cinquillo"],
        "notes": "",
    },
    {
        "fixture_id": "neg_all_onset_xxxxxxxx",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "any",
        "token_pattern": "xxxxxxxx",
        "accent_pattern": "XXXXXXXX",
        "interval_ratios": [],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2", "clave", "cinquillo"],
        "description": "All onset 8-step.",
        "should_match_strength": "weak",
        "should_not_match": ["tresillo_3_3_2", "clave", "cinquillo"],
        "notes": "",
    },
    {
        "fixture_id": "neg_all_rest",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "any",
        "token_pattern": "........",
        "accent_pattern": "........",
        "interval_ratios": [],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2", "clave", "backbeat"],
        "description": "All rests.",
        "should_match_strength": "weak",
        "should_not_match": ["tresillo_3_3_2", "clave", "backbeat"],
        "notes": "",
    },
    {
        "fixture_id": "neg_random_sparse",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "any",
        "token_pattern": "x.....x..",
        "accent_pattern": "x.....x..",
        "interval_ratios": [3.7, 2.4],
        "rotations": [],
        "negative_families": ["clave", "tresillo_3_3_2"],
        "description": "Random sparse pattern.",
        "should_match_strength": "weak",
        "should_not_match": ["clave", "tresillo_3_3_2"],
        "notes": "",
    },
    {
        "fixture_id": "neg_random_dense",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "any",
        "token_pattern": "xx.xx.xxx",
        "accent_pattern": "xx.xx.xxx",
        "interval_ratios": [0.8, 0.6, 0.7],
        "rotations": [],
        "negative_families": ["clave", "cinquillo"],
        "description": "Random dense pattern.",
        "should_match_strength": "weak",
        "should_not_match": ["clave", "cinquillo"],
        "notes": "",
    },
    {
        "fixture_id": "neg_single_onset",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "any",
        "token_pattern": "x.......",
        "accent_pattern": "X.......",
        "interval_ratios": [],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2", "backbeat"],
        "description": "Single onset.",
        "should_match_strength": "weak",
        "should_not_match": ["tresillo_3_3_2", "backbeat"],
        "notes": "",
    },
    {
        "fixture_id": "neg_repeated_no_shape",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "any",
        "token_pattern": "x...x...",
        "accent_pattern": "x...x...",
        "interval_ratios": [1.0, 1.0],
        "rotations": [],
        "negative_families": ["clave", "cinquillo"],
        "description": "Repeated but lacks historical shape evidence.",
        "should_match_strength": "weak",
        "should_not_match": ["clave", "cinquillo"],
        "notes": "",
    },
    {
        "fixture_id": "neg_straight_grid_without_accent",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "4/4",
        "token_pattern": "x.x.x.x.",
        "accent_pattern": "x.x.x.x.",
        "interval_ratios": [1.0, 1.0, 1.0, 1.0],
        "rotations": [],
        "negative_families": ["backbeat", "gospel_clap_backbeat"],
        "description": "Straight grid but no accent evidence.",
        "should_match_strength": "weak",
        "should_not_match": ["backbeat", "gospel_clap_backbeat"],
        "notes": "",
    },
    {
        "fixture_id": "neg_ambiguous_tresillo_habanera_like",
        "expected_pattern_id": None,
        "expected_family": None,
        "meter_context": "4/4",
        "token_pattern": "x..x..xx",
        "accent_pattern": "X..x..xx",
        "interval_ratios": [1.4, 1.4, 1.2],
        "rotations": [],
        "negative_families": ["tresillo_3_3_2", "habanera"],
        "description": "Intentionally ambiguous between tresillo/habanera family cues.",
        "should_match_strength": "ambiguous",
        "should_not_match": ["tresillo_3_3_2", "habanera"],
        "notes": "",
    },
]
