from __future__ import annotations

from typing import Any


THEORY_SOURCES: list[dict[str, Any]] = [
    {
        "source_id": "london_hearing_in_time",
        "title": "Hearing in Time",
        "author": "Justin London",
        "domain": "rhythm_time",
        "concepts": ["meter", "beat", "entrainment", "temporal_hierarchy"],
        "feature_targets": ["meter_time", "subdivision_grid", "pulse_stability"],
        "label_types_supported": ["derived_observation", "weak_label"],
        "useful_for": "Beat and meter hypothesis modeling",
        "limitations": "Theory framing, not direct algorithmic ground truth.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "hasty_meter_as_rhythm",
        "title": "Meter as Rhythm",
        "author": "Christopher Hasty",
        "domain": "rhythm_time",
        "concepts": ["processual_meter", "metric_ambiguity"],
        "feature_targets": ["meter_hypotheses", "ambiguity_score"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Ambiguous meter interpretation",
        "limitations": "Interpretive and context dependent.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "cooper_meyer_rhythmic_structure",
        "title": "The Rhythmic Structure of Music",
        "author": "Cooper & Meyer",
        "domain": "rhythm_time",
        "concepts": ["grouping", "accent", "metric_levels"],
        "feature_targets": ["phrase_rhythm", "accent_profiles"],
        "label_types_supported": ["derived_observation", "weak_label"],
        "useful_for": "Phrase and grouping cues",
        "limitations": "Symbolic abstractions need audio-context validation.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "toussaint_geometry_rhythm",
        "title": "The Geometry of Musical Rhythm",
        "author": "Godfried Toussaint",
        "domain": "rhythm_time",
        "concepts": ["rhythm_families", "cyclic_patterns", "euclidean_rhythm"],
        "feature_targets": ["rhythm_lexicon", "cycle_patterns"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Cycle and pattern family candidates",
        "limitations": "Pattern similarity does not imply cultural function.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "keil_feld_groove",
        "title": "Music Grooves",
        "author": "Keil & Feld",
        "domain": "rhythm_time",
        "concepts": ["participatory_discrepancy", "groove"],
        "feature_targets": ["microtiming", "humanization_score"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Microtiming and feel interpretation",
        "limitations": "Requires embodied/listener context.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "iyer_microtiming_embodied",
        "title": "Microtiming and Embodied Rhythm",
        "author": "Vijay Iyer",
        "domain": "rhythm_time",
        "concepts": ["microtiming", "embodiment", "expressive_deviation"],
        "feature_targets": ["microtiming_records"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Ahead/behind grid interpretation",
        "limitations": "Interpretive; cannot be hard-labeled from symbolic data alone.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "lefebvre_rhythmanalysis",
        "title": "Rhythmanalysis",
        "author": "Henri Lefebvre",
        "domain": "rhythm_time",
        "concepts": ["macroform", "cyclic_time", "social_rhythm"],
        "feature_targets": ["macro_time", "sectional_density_arcs"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Macro rhythm arcs and ritual arrival candidates",
        "limitations": "Philosophical framing, not mechanistic.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "arom_african_polyphony",
        "title": "African Polyphony and Polyrhythm",
        "author": "Simha Arom",
        "domain": "rhythm_time",
        "concepts": ["polyrhythm", "cycle", "interlocking"],
        "feature_targets": ["cycle_patterns", "phrase_rhythm"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Polyrhythmic cycle witnesses",
        "limitations": "Context-sensitive tradition-specific interpretation.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "kubik_theory_african_music",
        "title": "Theory of African Music",
        "author": "Gerhard Kubik",
        "domain": "rhythm_time",
        "concepts": ["timeline_patterns", "metrical_reference"],
        "feature_targets": ["cycle_patterns", "accent_skeletons"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Timeline/cycle pattern candidates",
        "limitations": "Requires cultural context to avoid overgeneralization.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "agawu_representing_african_music",
        "title": "Representing African Music",
        "author": "Kofi Agawu",
        "domain": "rhythm_time",
        "concepts": ["analytical_representation", "metrical_interpretation"],
        "feature_targets": ["meter_hypotheses", "cycle_patterns"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Representation-aware rhythm analysis",
        "limitations": "Not directly computational.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "chernoff_african_sensibility",
        "title": "African Rhythm and African Sensibility",
        "author": "John Miller Chernoff",
        "domain": "rhythm_time",
        "concepts": ["participation", "call_response", "rhythmic_dialogue"],
        "feature_targets": ["phrase_rhythm", "call_response_score"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Call-response and social-rhythm candidates",
        "limitations": "Ethnographic and interpretive.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "schoenberg_theory_harmony",
        "title": "Theory of Harmony",
        "author": "Arnold Schoenberg",
        "domain": "pitch_harmony",
        "concepts": ["functional_harmony", "voice_leading"],
        "feature_targets": ["harmony_sonority", "chord_movement"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Functional harmony candidate framing",
        "limitations": "Not universal across modal/atonal/nonfunctional music.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "hindemith_craft_composition",
        "title": "The Craft of Musical Composition",
        "author": "Paul Hindemith",
        "domain": "pitch_harmony",
        "concepts": ["interval_hierarchy", "harmonic_tension"],
        "feature_targets": ["interval_records", "tension_release_candidates"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Interval/tension proxies",
        "limitations": "Theory-specific assumptions.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "aldwell_schachter_voice_leading",
        "title": "Harmony and Voice Leading",
        "author": "Aldwell & Schachter",
        "domain": "pitch_harmony",
        "concepts": ["voice_leading", "cadence", "tonal_motion"],
        "feature_targets": ["chord_movement", "counterpoint"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Cadence and voice-leading candidates",
        "limitations": "Western tonal emphasis.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "fux_gradus_ad_parnassum",
        "title": "Gradus ad Parnassum",
        "author": "Johann Joseph Fux",
        "domain": "pitch_harmony",
        "concepts": ["counterpoint", "consonance_dissonance"],
        "feature_targets": ["counterpoint_records", "interval_consonance_profiles"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Counterpoint motion proxies",
        "limitations": "Species rules are historical constraints, not universal.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "persichetti_twentieth_century_harmony",
        "title": "Twentieth-Century Harmony",
        "author": "Vincent Persichetti",
        "domain": "pitch_harmony",
        "concepts": ["quartal_harmony", "clusters", "nonfunctional_harmony"],
        "feature_targets": ["sonority_types", "experimental_harmony_labels"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Cluster/quartal/ambiguous sonority candidates",
        "limitations": "Descriptive not deterministic.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "messiaen_technique_language",
        "title": "Technique of My Musical Language",
        "author": "Olivier Messiaen",
        "domain": "pitch_harmony",
        "concepts": ["modes_of_limited_transposition", "color_harmony"],
        "feature_targets": ["mode_candidates", "color_harmony_labels"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Modal/ambiguous center candidates",
        "limitations": "Composer-specific language.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "forte_structure_atonal",
        "title": "The Structure of Atonal Music",
        "author": "Allen Forte",
        "domain": "pitch_harmony",
        "concepts": ["pitch_class_set", "set_relations"],
        "feature_targets": ["active_pitch_classes", "set_family_candidates"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Atonal set and ambiguity analysis",
        "limitations": "Set labels are interpretive candidates.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "straus_post_tonal",
        "title": "Introduction to Post-Tonal Theory",
        "author": "Joseph Straus",
        "domain": "pitch_harmony",
        "concepts": ["post_tonal_motion", "set_theory"],
        "feature_targets": ["interval_records", "nonfunctional_harmony"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Post-tonal interval/harmony candidates",
        "limitations": "Not direct ground truth labels.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "lewin_gmIt",
        "title": "Generalized Musical Intervals and Transformations",
        "author": "David Lewin",
        "domain": "pitch_harmony",
        "concepts": ["transformations", "interval_networks"],
        "feature_targets": ["chord_movement", "interval_transforms"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Transformational relation candidates",
        "limitations": "High-interpretation analytical layer.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "tymoczko_geometry_music",
        "title": "A Geometry of Music",
        "author": "Dmitri Tymoczko",
        "domain": "pitch_harmony",
        "concepts": ["voice_leading_geometry", "chord_space"],
        "feature_targets": ["voice_leading_distance", "chord_movement"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Voice-leading distance proxies",
        "limitations": "Geometric model assumptions.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "cohn_audacious_euphony",
        "title": "Audacious Euphony",
        "author": "Richard Cohn",
        "domain": "pitch_harmony",
        "concepts": ["hexatonic", "neo_riemannian"],
        "feature_targets": ["chord_relation_candidates"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Chromatic relation candidates",
        "limitations": "Specific chromatic-romantic repertoire emphasis.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "partch_genesis_music",
        "title": "Genesis of a Music",
        "author": "Harry Partch",
        "domain": "pitch_harmony",
        "concepts": ["microtonality", "just_intonation"],
        "feature_targets": ["tuning_system_records", "microtonal_candidates"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Microtonal/tuning-system candidates",
        "limitations": "Needs pitch-accuracy evidence beyond symbolic MIDI.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "cowell_new_musical_resources",
        "title": "New Musical Resources",
        "author": "Henry Cowell",
        "domain": "pitch_harmony",
        "concepts": ["tone_clusters", "extended_harmony"],
        "feature_targets": ["cluster_density", "experimental_harmony"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Cluster/color harmony candidates",
        "limitations": "Interpretive style labeling.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "xenakis_formalized_music",
        "title": "Formalized Music",
        "author": "Iannis Xenakis",
        "domain": "pitch_harmony",
        "concepts": ["stochastic_structures", "nonfunctional_harmony"],
        "feature_targets": ["macro_harmonic_form_candidates"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Non-tonal macroform candidates",
        "limitations": "Requires model-specific assumptions.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "berliner_thinking_in_jazz",
        "title": "Thinking in Jazz",
        "author": "Paul Berliner",
        "domain": "pitch_harmony",
        "concepts": ["jazz_harmony", "improvisational_voice_leading"],
        "feature_targets": ["chord_movement", "counterpoint_records"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Jazz/gospel ambiguity and movement candidates",
        "limitations": "Ethnographic; not algorithmic certainty.",
        "trust_policy": "theory_reference",
    },
    {
        "source_id": "russell_lydian_chromatic",
        "title": "The Lydian Chromatic Concept",
        "author": "George Russell",
        "domain": "pitch_harmony",
        "concepts": ["modal_center", "chromatic_approach"],
        "feature_targets": ["key_hypotheses", "modal_center_candidates"],
        "label_types_supported": ["weak_label"],
        "useful_for": "Modal and chromatic center hypotheses",
        "limitations": "Conceptual interpretation, not proof.",
        "trust_policy": "theory_reference",
    },
]


def get_theory_sources_for_concept(concept: str) -> list[dict[str, Any]]:
    needle = concept.strip().lower()
    return [item for item in THEORY_SOURCES if any(needle == str(c).lower() for c in item.get("concepts", []))]


def get_feature_targets_for_theory_source(source_id: str) -> list[str]:
    for item in THEORY_SOURCES:
        if str(item.get("source_id")) == source_id:
            targets = item.get("feature_targets", [])
            return [str(value) for value in targets] if isinstance(targets, list) else []
    return []


def annotate_feature_with_theory_sources(feature_record: dict[str, Any]) -> dict[str, Any]:
    targets = feature_record.get("feature_targets", [])
    if not isinstance(targets, list):
        targets = []
    refs = [
        item["source_id"]
        for item in THEORY_SOURCES
        if any(str(t) in item.get("feature_targets", []) for t in targets)
    ]
    feature_record["theory_source_refs"] = sorted(set(refs))
    return feature_record


def annotate_label_with_theory_sources(label_record: dict[str, Any]) -> dict[str, Any]:
    label_type = str(label_record.get("label_type", "")).strip().lower()
    refs = [
        item["source_id"]
        for item in THEORY_SOURCES
        if label_type and label_type in [str(v).lower() for v in item.get("label_types_supported", [])]
    ]
    label_record["theory_source_refs"] = sorted(set(refs))
    return label_record
