from __future__ import annotations

from typing import Any


TaskPolicy = dict[str, Any]

SPLIT_THRESHOLDS = {
    "train": 0.72,
    "validation": 0.60,
    "review": 0.35,
}

CRITICAL_BLOCKERS = {
    "missing_target_range",
    "missing_target_midi_ref",
    "no_target_events",
    "invalid_timing",
    "silence_or_noise_target",
    "malformed_refs",
}

MAJOR_BLOCKERS = {
    "task_policy_failed",
    "low_transcription_reliability",
}

NON_CRITICAL_WEAKNESSES = {
    "missing_external_witness_refs",
    "weak_style_labels",
    "ambiguous_key_or_chord",
    "missing_human_verification",
}

SOFT_BLOCKERS = {
    "route_state_unsuitable",
    "phrase_boundary_weak",
    "weak_or_missing_task_evidence",
}

EVIDENCE_BOOSTERS: dict[str, list[str]] = {
    "continuation": ["compatible_state_pairing", "long_form_context"],
    "phrase_continuation": ["phrase_boundary_evidence", "density_boundary_change"],
    "call_response": ["density_arc_response", "rhythmic_contrast_response"],
    "harmony_continuation": ["pitch_harmony_overlap", "meter_time_support"],
    "melody_continuation": ["pitch_harmony_overlap", "motif_or_contour_support"],
}


def _policy(
    *,
    allowed_content_states: list[str],
    required_feature_refs: list[str],
    minimum_duration: float,
    maximum_duration: float,
    minimum_note_count: int,
    preferred_trust_status: str,
    target_domains: list[str],
    weak_label_usage_policy: str,
    review_policy: str,
) -> TaskPolicy:
    return {
        "allowed_content_states": allowed_content_states,
        "required_feature_refs": required_feature_refs,
        "minimum_duration": minimum_duration,
        "maximum_duration": maximum_duration,
        "minimum_note_count": minimum_note_count,
        "preferred_trust_status": preferred_trust_status,
        "target_domains": target_domains,
        "weak_label_usage_policy": weak_label_usage_policy,
        "review_policy": review_policy,
    }


TASK_POLICIES: dict[str, TaskPolicy] = {
    "continuation": _policy(
        allowed_content_states=["rhythm_dominant", "harmonic_dominant", "melodic_lead", "polyphonic_full_mix", "vocal_dominant", "rap_vocal_dominant"],
        required_feature_refs=["rhythm_features", "harmony_features"],
        minimum_duration=4.0,
        maximum_duration=120.0,
        minimum_note_count=2,
        preferred_trust_status="accepted_or_review",
        target_domains=["rhythm", "timing", "pitch", "density"],
        weak_label_usage_policy="conditioning_only",
        review_policy="route/content mismatch -> review",
    ),
    "phrase_continuation": _policy(
        allowed_content_states=["melodic_lead", "vocal_dominant", "rap_vocal_dominant", "harmonic_dominant", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "pitch_harmony_features"],
        minimum_duration=6.0,
        maximum_duration=180.0,
        minimum_note_count=2,
        preferred_trust_status="accepted_or_review",
        target_domains=["phrase", "contour", "harmony", "meter"],
        weak_label_usage_policy="conditioning_only",
        review_policy="low phrase quality -> review",
    ),
    "groove_continuation": _policy(
        allowed_content_states=["rhythm_dominant", "percussive_only", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "meter_time_features"],
        minimum_duration=2.0,
        maximum_duration=90.0,
        minimum_note_count=2,
        preferred_trust_status="accepted_or_review",
        target_domains=["rhythm", "timing", "velocity", "density"],
        weak_label_usage_policy="conditioning_only",
        review_policy="missing external beat witness -> review",
    ),
    "harmony_continuation": _policy(
        allowed_content_states=["harmonic_dominant", "polyphonic_full_mix"],
        required_feature_refs=["harmony_features", "pitch_harmony_features"],
        minimum_duration=4.0,
        maximum_duration=120.0,
        minimum_note_count=2,
        preferred_trust_status="accepted_or_review",
        target_domains=["pitch", "sonority", "chord_movement", "voice_leading"],
        weak_label_usage_policy="conditioning_only",
        review_policy="tonal conflict -> review",
    ),
    "melody_continuation": _policy(
        allowed_content_states=["melodic_lead", "vocal_dominant", "polyphonic_full_mix", "rap_vocal_dominant"],
        required_feature_refs=["pitch_harmony_features", "rhythm_features"],
        minimum_duration=3.0,
        maximum_duration=90.0,
        minimum_note_count=2,
        preferred_trust_status="accepted_or_review",
        target_domains=["contour", "intervals", "register", "rhythm"],
        weak_label_usage_policy="conditioning_only",
        review_policy="low contour confidence -> review",
    ),
    "call_response": _policy(
        allowed_content_states=["vocal_dominant", "rap_vocal_dominant", "melodic_lead", "rhythm_dominant", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "pitch_harmony_features"],
        minimum_duration=2.0,
        maximum_duration=90.0,
        minimum_note_count=2,
        preferred_trust_status="accepted_or_review",
        target_domains=["phrasing", "motif", "register", "rhythm"],
        weak_label_usage_policy="conditioning_only",
        review_policy="weak call-response evidence -> review",
    ),
    "motif_transformation": _policy(
        allowed_content_states=["rhythm_dominant", "melodic_lead", "polyphonic_full_mix", "harmonic_dominant"],
        required_feature_refs=["rhythm_features", "pitch_harmony_features"],
        minimum_duration=1.5,
        maximum_duration=60.0,
        minimum_note_count=2,
        preferred_trust_status="review",
        target_domains=["motif", "transformation", "timing", "pitch"],
        weak_label_usage_policy="conditioning_only",
        review_policy="always review if motif strength is weak",
    ),
    "section_transition": _policy(
        allowed_content_states=["rhythm_dominant", "harmonic_dominant", "melodic_lead", "polyphonic_full_mix", "vocal_dominant"],
        required_feature_refs=["meter_time_features", "pitch_harmony_features"],
        minimum_duration=6.0,
        maximum_duration=180.0,
        minimum_note_count=2,
        preferred_trust_status="review",
        target_domains=["macro_form", "transition", "density", "tonal_motion"],
        weak_label_usage_policy="conditioning_only",
        review_policy="ambiguous transition -> review",
    ),
    "buildup_to_release": _policy(
        allowed_content_states=["rhythm_dominant", "harmonic_dominant", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "meter_time_features", "harmony_features"],
        minimum_duration=6.0,
        maximum_duration=180.0,
        minimum_note_count=2,
        preferred_trust_status="review",
        target_domains=["dynamics", "density", "release", "cadence"],
        weak_label_usage_policy="conditioning_only",
        review_policy="missing density arc evidence -> review",
    ),
    "infill_missing_region": _policy(
        allowed_content_states=["non_silence_any"],
        required_feature_refs=["rhythm_features", "harmony_features", "pitch_harmony_features"],
        minimum_duration=1.0,
        maximum_duration=60.0,
        minimum_note_count=1,
        preferred_trust_status="review",
        target_domains=["infill", "timing", "voice_leading", "arrangement"],
        weak_label_usage_policy="conditioning_only",
        review_policy="low-context continuity -> review",
    ),
    # Forward-compatible policy entries for additional generation tasks.
    "variation": _policy(
        allowed_content_states=["melodic_lead", "rhythm_dominant", "harmonic_dominant", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "pitch_harmony_features"],
        minimum_duration=2.0,
        maximum_duration=90.0,
        minimum_note_count=6,
        preferred_trust_status="review",
        target_domains=["motif", "variation", "rhythm", "pitch"],
        weak_label_usage_policy="conditioning_only",
        review_policy="novelty mismatch -> review",
    ),
    "drum_to_harmony_entry": _policy(
        allowed_content_states=["percussive_only", "rhythm_dominant", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "harmony_features"],
        minimum_duration=2.0,
        maximum_duration=90.0,
        minimum_note_count=6,
        preferred_trust_status="review",
        target_domains=["entry", "arrangement", "harmony"],
        weak_label_usage_policy="conditioning_only",
        review_policy="weak harmonic entry evidence -> review",
    ),
    "bassline_continuation": _policy(
        allowed_content_states=["harmonic_dominant", "polyphonic_full_mix"],
        required_feature_refs=["pitch_harmony_features", "harmony_features"],
        minimum_duration=2.0,
        maximum_duration=90.0,
        minimum_note_count=6,
        preferred_trust_status="review",
        target_domains=["bass_motion", "harmony", "rhythm"],
        weak_label_usage_policy="conditioning_only",
        review_policy="low bass register evidence -> review",
    ),
    "reharmonization_candidate": _policy(
        allowed_content_states=["harmonic_dominant", "polyphonic_full_mix"],
        required_feature_refs=["harmony_features", "pitch_harmony_features"],
        minimum_duration=4.0,
        maximum_duration=120.0,
        minimum_note_count=8,
        preferred_trust_status="review",
        target_domains=["harmony", "sonority", "cadence"],
        weak_label_usage_policy="conditioning_only",
        review_policy="conflicted tonal witness -> review",
    ),
    "counterpoint_response": _policy(
        allowed_content_states=["melodic_lead", "polyphonic_full_mix", "harmonic_dominant"],
        required_feature_refs=["pitch_harmony_features"],
        minimum_duration=3.0,
        maximum_duration=90.0,
        minimum_note_count=8,
        preferred_trust_status="review",
        target_domains=["counterpoint", "voice_independence", "intervals"],
        weak_label_usage_policy="conditioning_only",
        review_policy="counterpoint ambiguity -> review",
    ),
    "sparse_to_dense_arrangement": _policy(
        allowed_content_states=["sparse_activity", "rhythm_dominant", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "meter_time_features"],
        minimum_duration=4.0,
        maximum_duration=120.0,
        minimum_note_count=6,
        preferred_trust_status="review",
        target_domains=["arrangement", "density_arc", "groove"],
        weak_label_usage_policy="conditioning_only",
        review_policy="weak density arc -> review",
    ),
    "texture_transfer": _policy(
        allowed_content_states=["polyphonic_full_mix", "harmonic_dominant", "rhythm_dominant"],
        required_feature_refs=["rhythm_features", "pitch_harmony_features"],
        minimum_duration=4.0,
        maximum_duration=120.0,
        minimum_note_count=8,
        preferred_trust_status="review",
        target_domains=["texture", "density", "sonority"],
        weak_label_usage_policy="conditioning_only",
        review_policy="style ambiguity -> review",
    ),
    "style_conditioned_generation": _policy(
        allowed_content_states=["rhythm_dominant", "harmonic_dominant", "melodic_lead", "polyphonic_full_mix"],
        required_feature_refs=["tags", "rhythm_features", "pitch_harmony_features"],
        minimum_duration=3.0,
        maximum_duration=120.0,
        minimum_note_count=8,
        preferred_trust_status="review",
        target_domains=["style", "groove", "harmony", "contour"],
        weak_label_usage_policy="conditioning_only_never_ground_truth",
        review_policy="all style labels remain weak unless human-verified",
    ),
    "audio_to_midi_prediction": _policy(
        allowed_content_states=["rhythm_dominant", "harmonic_dominant", "melodic_lead", "polyphonic_full_mix", "vocal_dominant"],
        required_feature_refs=["rhythm_features", "harmony_features"],
        minimum_duration=2.0,
        maximum_duration=120.0,
        minimum_note_count=8,
        preferred_trust_status="accepted_or_review",
        target_domains=["transcription", "timing", "pitch"],
        weak_label_usage_policy="conditioning_only",
        review_policy="low reliability -> review",
    ),
    "analysis_conditioned_midi_generation": _policy(
        allowed_content_states=["rhythm_dominant", "harmonic_dominant", "melodic_lead", "polyphonic_full_mix"],
        required_feature_refs=["rhythm_features", "harmony_features", "meter_time_features", "pitch_harmony_features"],
        minimum_duration=2.0,
        maximum_duration=120.0,
        minimum_note_count=8,
        preferred_trust_status="review",
        target_domains=["analysis_conditioning", "midi_generation"],
        weak_label_usage_policy="conditioning_only",
        review_policy="analysis uncertainty -> review",
    ),
    "next_section_prediction": _policy(
        allowed_content_states=["rhythm_dominant", "harmonic_dominant", "melodic_lead", "polyphonic_full_mix", "vocal_dominant"],
        required_feature_refs=["meter_time_features", "pitch_harmony_features", "routing"],
        minimum_duration=6.0,
        maximum_duration=180.0,
        minimum_note_count=10,
        preferred_trust_status="review",
        target_domains=["macro_form", "transition", "sectional_prediction"],
        weak_label_usage_policy="conditioning_only",
        review_policy="section label uncertainty -> review",
    ),
}

